# Importaciones

In [21]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data

In [22]:
salud = pd.read_csv('salud_limpio_MICE.csv')

In [23]:
salud

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,diagnostico_hipertension,poco_interes_14d,deprimido_14d,problema_dormir_14d,...,area_residencia,lugar_residencia,codigo_ubicacion_geo,num_conglomerado,codigo_centro_poblado,nombre_centro_poblado,longitud,latitud,imc,phq9
0,2019,100201,completa,2,mujer,33.0,no,0.0,0.0,0.0,...,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,26.355556,0.0
1,2019,102801,completa,2,mujer,36.0,no,1.0,0.0,0.0,...,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,32.724838,1.0
2,2019,104801,completa,2,mujer,28.0,no,0.0,0.0,0.0,...,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,34.132280,0.0
3,2019,113601,completa,2,mujer,30.0,no,1.0,1.0,0.0,...,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,24.638117,3.0
4,2019,116701,completa,1,mujer,18.0,no,0.0,0.0,0.0,...,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,19.086083,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71.0,no,0.0,1.0,3.0,...,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538,26.104897,7.0
140827,2023,542903101,completa,1,hombre,64.0,no,0.0,0.0,0.0,...,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538,24.533033,0.0
140828,2023,542904501,completa,2,mujer,56.0,no,0.0,0.0,0.0,...,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538,25.117073,1.0
140829,2023,542904701,completa,1,hombre,67.0,si,3.0,3.0,0.0,...,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538,26.770831,9.0
140830,2023,542905001,completa,2,mujer,57.0,si,3.0,3.0,0.0,...,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538,24.937539,17.0

# Columnas

## salud_mental

In [24]:
#función para categorizar salud mental 
def salud_mental(x):
    if x == 0:
        return 'no depresion'
    elif x >= 1 and x <= 4:
        return 'depresion minima'
    elif x >= 5 and x <= 9:
        return 'depresion leve'
    elif x >= 10 and x <= 14:
        return 'depresion moderada'
    elif x >= 15 and x <= 19:
        return 'depresion moderadamente severa'
    elif x >= 20 and x <= 27:
        return 'depresion severa'
    else:
        return 'error en suma'

In [25]:
#Sumar por fila las respuestas de la escala PHQ-9
salud['phq9'] = salud.iloc[:, 7:16].sum(axis=1)

In [26]:
#aplicar función de salud mental
salud['salud_mental'] = salud['phq9'].apply(salud_mental)

In [27]:
# eliminar las columnas de las preguntas de la escala PHQ-9
salud = salud.drop(['poco_interes_14d', 'deprimido_14d', 'problema_dormir_14d','cansancio_14d', 'problema_comer_14d', 'problema_atencion_14d','problema_moverse_14d', 'pensamiento_suicida_14d', 'sentirse_mal_14d'], axis=1)
salud

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,diagnostico_hipertension,peso_kg,talla_cm,presion_sis_1,...,lugar_residencia,codigo_ubicacion_geo,num_conglomerado,codigo_centro_poblado,nombre_centro_poblado,longitud,latitud,imc,phq9,salud_mental
0,2019,100201,completa,2,mujer,33.0,no,59.3,150.0,97.0,...,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,26.355556,0.0,no depresion
1,2019,102801,completa,2,mujer,36.0,no,84.3,160.5,115.0,...,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,32.724838,1.0,depresion minima
2,2019,104801,completa,2,mujer,28.0,no,85.1,157.9,135.0,...,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,34.132280,0.0,no depresion
3,2019,113601,completa,2,mujer,30.0,no,57.6,152.9,102.0,...,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,24.638117,3.0,depresion minima
4,2019,116701,completa,1,mujer,18.0,no,45.5,154.4,123.0,...,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320,19.086083,0.0,no depresion
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71.0,no,57.8,148.8,139.0,...,campo,180202,4381201,1,chojata,-70.73015,-16.388538,26.104897,7.0,depresion leve
140827,2023,542903101,completa,1,hombre,64.0,no,62.1,159.1,117.0,...,campo,180202,4381201,1,chojata,-70.73015,-16.388538,24.533033,0.0,no depresion
140828,2023,542904501,completa,2,mujer,56.0,no,52.3,144.3,107.0,...,campo,180202,4381201,1,chojata,-70.73015,-16.388538,25.117073,1.0,depresion minima
140829,2023,542904701,completa,1,hombre,67.0,si,67.0,158.2,126.0,...,campo,180202,4381201,1,chojata,-70.73015,-16.388538,26.770831,9.0,depresion leve
140830,2023,542905001,completa,2,mujer,57.0,si,58.3,152.9,115.0,...,campo,180202,4381201,1,chojata,-70.73015,-16.388538,24.937539,17.0,depresion moderadamente severa

## categoria_imc

In [28]:
#función para categorizar imc
def obesidad(x):
    if x < 18.5:
        return 'bajo'
    elif x >= 18.5 and x <= 24.9:
        return 'normal'
    elif x >= 25 and x <= 29.9:
        return 'sobrepeso'
    elif x >= 30 and x <= 34.9:
        return 'obesidad 1'
    elif x >= 35 and x <= 39.9:
        return 'obesidad 2'
    else:
        return 'obesidad 3'

In [29]:
#cálculo de imc
salud["imc"] = salud["peso_kg"] / (salud["talla_cm"] / 100) ** 2
salud["imc"] = salud["imc"].round(2)

In [30]:
#aplicar función de imc
salud['categoria_imc'] = salud['imc'].apply(obesidad)
salud

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,diagnostico_hipertension,peso_kg,talla_cm,presion_sis_1,...,codigo_ubicacion_geo,num_conglomerado,codigo_centro_poblado,nombre_centro_poblado,longitud,latitud,imc,phq9,salud_mental,categoria_imc
0,2019,100201,completa,2,mujer,33.0,no,59.3,150.0,97.0,...,10101,7065,1,chachapoyas,-77.87383,-6.223320,26.36,0.0,no depresion,sobrepeso
1,2019,102801,completa,2,mujer,36.0,no,84.3,160.5,115.0,...,10101,7065,1,chachapoyas,-77.87383,-6.223320,32.72,1.0,depresion minima,obesidad 1
2,2019,104801,completa,2,mujer,28.0,no,85.1,157.9,135.0,...,10101,7065,1,chachapoyas,-77.87383,-6.223320,34.13,0.0,no depresion,obesidad 1
3,2019,113601,completa,2,mujer,30.0,no,57.6,152.9,102.0,...,10101,7065,1,chachapoyas,-77.87383,-6.223320,24.64,3.0,depresion minima,normal
4,2019,116701,completa,1,mujer,18.0,no,45.5,154.4,123.0,...,10101,7065,1,chachapoyas,-77.87383,-6.223320,19.09,0.0,no depresion,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71.0,no,57.8,148.8,139.0,...,180202,4381201,1,chojata,-70.73015,-16.388538,26.10,7.0,depresion leve,sobrepeso
140827,2023,542903101,completa,1,hombre,64.0,no,62.1,159.1,117.0,...,180202,4381201,1,chojata,-70.73015,-16.388538,24.53,0.0,no depresion,normal
140828,2023,542904501,completa,2,mujer,56.0,no,52.3,144.3,107.0,...,180202,4381201,1,chojata,-70.73015,-16.388538,25.12,1.0,depresion minima,sobrepeso
140829,2023,542904701,completa,1,hombre,67.0,si,67.0,158.2,126.0,...,180202,4381201,1,chojata,-70.73015,-16.388538,26.77,9.0,depresion leve,sobrepeso
140830,2023,542905001,completa,2,mujer,57.0,si,58.3,152.9,115.0,...,180202,4381201,1,chojata,-70.73015,-16.388538,24.94,17.0,depresion moderadamente severa,obesidad 3

## diagnostico_obesidad

In [31]:
#función para diagnostico obesidad 
def diagnostico_obesidad(x):
    if x >= 30:
        return 'si'
    else:
        return 'no'

In [32]:
#aplicar función de diagnostico obesidad
salud['diagnostico_obesidad'] = salud['imc'].apply(diagnostico_obesidad)

In [33]:
#elminar columnas de peso, talla
salud = salud.drop(['peso_kg', 'talla_cm'], axis=1)
salud

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,diagnostico_hipertension,presion_sis_1,presion_dia_1,presion_sis_2,...,num_conglomerado,codigo_centro_poblado,nombre_centro_poblado,longitud,latitud,imc,phq9,salud_mental,categoria_imc,diagnostico_obesidad
0,2019,100201,completa,2,mujer,33.0,no,97.0,62.0,102.0,...,7065,1,chachapoyas,-77.87383,-6.223320,26.36,0.0,no depresion,sobrepeso,no
1,2019,102801,completa,2,mujer,36.0,no,115.0,75.0,106.0,...,7065,1,chachapoyas,-77.87383,-6.223320,32.72,1.0,depresion minima,obesidad 1,si
2,2019,104801,completa,2,mujer,28.0,no,135.0,74.0,133.0,...,7065,1,chachapoyas,-77.87383,-6.223320,34.13,0.0,no depresion,obesidad 1,si
3,2019,113601,completa,2,mujer,30.0,no,102.0,69.0,95.0,...,7065,1,chachapoyas,-77.87383,-6.223320,24.64,3.0,depresion minima,normal,no
4,2019,116701,completa,1,mujer,18.0,no,123.0,74.0,112.0,...,7065,1,chachapoyas,-77.87383,-6.223320,19.09,0.0,no depresion,normal,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71.0,no,139.0,80.0,129.0,...,4381201,1,chojata,-70.73015,-16.388538,26.10,7.0,depresion leve,sobrepeso,no
140827,2023,542903101,completa,1,hombre,64.0,no,117.0,82.0,112.0,...,4381201,1,chojata,-70.73015,-16.388538,24.53,0.0,no depresion,normal,no
140828,2023,542904501,completa,2,mujer,56.0,no,107.0,75.0,106.0,...,4381201,1,chojata,-70.73015,-16.388538,25.12,1.0,depresion minima,sobrepeso,no
140829,2023,542904701,completa,1,hombre,67.0,si,126.0,78.0,130.0,...,4381201,1,chojata,-70.73015,-16.388538,26.77,9.0,depresion leve,sobrepeso,no
140830,2023,542905001,completa,2,mujer,57.0,si,115.0,71.0,126.0,...,4381201,1,chojata,-70.73015,-16.388538,24.94,17.0,depresion moderadamente severa,obesidad 3,no

## categoria_presion

In [34]:
#función para categoria presion
def categoria_presion (sistolica,diastolica):
    if sistolica < 120 and diastolica < 80:
        return "normal"
    elif sistolica >= 120 and sistolica <=129  and diastolica < 80:
        return "elevado"
    elif sistolica >= 130 and sistolica <=139  or diastolica >= 80 and diastolica <= 89:
        return "hipertension etapa 1"
    elif sistolica >= 140 and sistolica < 180 or diastolica >= 90 and diastolica <= 120:
        return "hipertension etapa 2"
    elif sistolica >= 180 or diastolica > 120:
        return "crisis hipertensiva"
    else:
        return "error"

In [35]:
#calcular el promedio de la presion sistolica y diastolica
salud["media_sis"] = salud[["presion_sis_1", "presion_sis_2"]].mean(axis=1)
salud["media_dia"] = salud[["presion_dia_1", "presion_dia_2"]].mean(axis=1)

#redondear media_sis y media dia a enteros
salud["media_sis"] = salud["media_sis"].round(0).astype(int)
salud["media_dia"] = salud["media_dia"].round(0).astype(int)

In [36]:
#aplicar función de categoria presion
salud['categoria_presion'] = salud.apply(lambda x: categoria_presion(x['media_sis'], x['media_dia']), axis=1)

In [37]:
print(salud["categoria_presion"].value_counts())

categoria_presion
normal                  74318
hipertension etapa 1    37018
elevado                 18967
hipertension etapa 2    10340
crisis hipertensiva       188
Name: count, dtype: int64

In [38]:
#eliminar columnas de presiones y medias de presiones
salud = salud.drop(['presion_sis_1', 'presion_sis_2', 'presion_dia_1', 'presion_dia_2'], axis=1)
salud

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,diagnostico_hipertension,region,area_residencia,lugar_residencia,...,longitud,latitud,imc,phq9,salud_mental,categoria_imc,diagnostico_obesidad,media_sis,media_dia,categoria_presion
0,2019,100201,completa,2,mujer,33.0,no,amazonas,urbano,pequena_ciudad,...,-77.87383,-6.223320,26.36,0.0,no depresion,sobrepeso,no,100,60,normal
1,2019,102801,completa,2,mujer,36.0,no,amazonas,urbano,pequena_ciudad,...,-77.87383,-6.223320,32.72,1.0,depresion minima,obesidad 1,si,110,75,normal
2,2019,104801,completa,2,mujer,28.0,no,amazonas,urbano,pequena_ciudad,...,-77.87383,-6.223320,34.13,0.0,no depresion,obesidad 1,si,134,76,hipertension etapa 1
3,2019,113601,completa,2,mujer,30.0,no,amazonas,urbano,pequena_ciudad,...,-77.87383,-6.223320,24.64,3.0,depresion minima,normal,no,98,65,normal
4,2019,116701,completa,1,mujer,18.0,no,amazonas,urbano,pequena_ciudad,...,-77.87383,-6.223320,19.09,0.0,no depresion,normal,no,118,72,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71.0,no,moquegua,rural,campo,...,-70.73015,-16.388538,26.10,7.0,depresion leve,sobrepeso,no,134,78,hipertension etapa 1
140827,2023,542903101,completa,1,hombre,64.0,no,moquegua,rural,campo,...,-70.73015,-16.388538,24.53,0.0,no depresion,normal,no,114,82,hipertension etapa 1
140828,2023,542904501,completa,2,mujer,56.0,no,moquegua,rural,campo,...,-70.73015,-16.388538,25.12,1.0,depresion minima,sobrepeso,no,106,76,normal
140829,2023,542904701,completa,1,hombre,67.0,si,moquegua,rural,campo,...,-70.73015,-16.388538,26.77,9.0,depresion leve,sobrepeso,no,128,80,hipertension etapa 1
140830,2023,542905001,completa,2,mujer,57.0,si,moquegua,rural,campo,...,-70.73015,-16.388538,24.94,17.0,depresion moderadamente severa,obesidad 3,no,120,74,elevado

In [39]:
#ordenar columnas
salud = salud[[
    "anio",
    "id_hogar",
    "cod_resultado",
    "cod_persona",
    "sexo",
    "edad",
    "media_sis",
    "media_dia",
    "categoria_presion",
    "diagnostico_hipertension",
    "phq9",
    "salud_mental",
    "imc",
    "categoria_imc",
    "diagnostico_obesidad",
    "region",
    "area_residencia",
    "lugar_residencia",
    "codigo_ubicacion_geo",
    "num_conglomerado",
    "codigo_centro_poblado",
    "nombre_centro_poblado",
    "longitud",
    "latitud"
]]

#df final de salud
salud

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,media_sis,media_dia,categoria_presion,diagnostico_hipertension,...,diagnostico_obesidad,region,area_residencia,lugar_residencia,codigo_ubicacion_geo,num_conglomerado,codigo_centro_poblado,nombre_centro_poblado,longitud,latitud
0,2019,100201,completa,2,mujer,33.0,100,60,normal,no,...,no,amazonas,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320
1,2019,102801,completa,2,mujer,36.0,110,75,normal,no,...,si,amazonas,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320
2,2019,104801,completa,2,mujer,28.0,134,76,hipertension etapa 1,no,...,si,amazonas,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320
3,2019,113601,completa,2,mujer,30.0,98,65,normal,no,...,no,amazonas,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320
4,2019,116701,completa,1,mujer,18.0,118,72,normal,no,...,no,amazonas,urbano,pequena_ciudad,10101,7065,1,chachapoyas,-77.87383,-6.223320
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71.0,134,78,hipertension etapa 1,no,...,no,moquegua,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538
140827,2023,542903101,completa,1,hombre,64.0,114,82,hipertension etapa 1,no,...,no,moquegua,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538
140828,2023,542904501,completa,2,mujer,56.0,106,76,normal,no,...,no,moquegua,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538
140829,2023,542904701,completa,1,hombre,67.0,128,80,hipertension etapa 1,si,...,no,moquegua,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538
140830,2023,542905001,completa,2,mujer,57.0,120,74,elevado,si,...,no,moquegua,rural,campo,180202,4381201,1,chojata,-70.73015,-16.388538

In [40]:
#guardar archivo csv
salud.to_csv('saud_endes_MICE.csv', index=False)