# Importaciones

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Data

## Health crime prevalencia

In [3]:
final = pd.read_excel('Health_crime_dta_prevalencia.xlsx')
final = final.drop(columns=['Unnamed: 0'])
final

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,media_sis,media_dia,categoria_presion,diagnostico_hipertension,...,latitud,geometry,incidencia_patrimonio,incidencia_libertad,incidencia_seguridad,incidencia_tranquilidad,incidencia_vida,incidencia_otros,Prev_hyp_year,Prev_ob_year
0,2019,100201,completa,2,mujer,33,100,60,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
1,2019,102801,completa,2,mujer,36,110,75,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
2,2019,104801,completa,2,mujer,28,134,76,hipertension etapa 1,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
3,2019,113601,completa,2,mujer,30,98,65,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
4,2019,116701,completa,1,mujer,18,118,72,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71,134,78,hipertension etapa 1,no,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140827,2023,542903101,completa,1,hombre,64,114,82,hipertension etapa 1,no,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140828,2023,542904501,completa,2,mujer,56,106,76,normal,no,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140829,2023,542904701,completa,1,hombre,67,128,80,hipertension etapa 1,si,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140830,2023,542905001,completa,2,mujer,57,120,74,elevado,si,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058

### Limpieza

In [4]:
#eliminar las filas que tengan de latitud -75.7474
final = final[~final['latitud'].isin([-75.7474])]

# Efilas con una longitud menor a -50
final = final[final['longitud'] <= -50]
final

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,media_sis,media_dia,categoria_presion,diagnostico_hipertension,...,latitud,geometry,incidencia_patrimonio,incidencia_libertad,incidencia_seguridad,incidencia_tranquilidad,incidencia_vida,incidencia_otros,Prev_hyp_year,Prev_ob_year
0,2019,100201,completa,2,mujer,33,100,60,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
1,2019,102801,completa,2,mujer,36,110,75,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
2,2019,104801,completa,2,mujer,28,134,76,hipertension etapa 1,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
3,2019,113601,completa,2,mujer,30,98,65,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
4,2019,116701,completa,1,mujer,18,118,72,normal,no,...,-6.223320,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.48258,973.899585,617.888327,29.098652,17.743080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542901901,completa,2,mujer,71,134,78,hipertension etapa 1,no,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140827,2023,542903101,completa,1,hombre,64,114,82,hipertension etapa 1,no,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140828,2023,542904501,completa,2,mujer,56,106,76,normal,no,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140829,2023,542904701,completa,1,hombre,67,128,80,hipertension etapa 1,si,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058
140830,2023,542905001,completa,2,mujer,57,120,74,elevado,si,...,-16.388538,POINT (-70.73015 -16.38853833),1672.972512,263.942274,248.386741,7.02508,2153.186877,1130.536014,28.205128,41.770058

## Geogps Perú

In [5]:
import geopandas as gpd

c:\Users\dial_\anaconda3\envs\endes_env\Lib\site-packages\pyproj\__init__.py:89: UserWarning: pyproj unable to set database path.
  _pyproj_global_context_initialize()

In [ ]:
shapefile_path = r"..\Departamental INEI 2023 geogpsperu SuyoPomalia\Departamental INEI 2023 geogpsperu SuyoPomalia.shp"
departamentos = gpd.read_file(shapefile_path)

print(departamentos.columns)

Index(['CCDD', 'DEPARTAMEN', 'OBJECTID', 'ESRI_OID', 'geometry'], dtype='object')

In [8]:
cols_interes = [
    'DEPARTAMEN',
    'geometry'
]

departamentos = departamentos[cols_interes]
departamentos = departamentos.rename(columns={'DEPARTAMEN': 'departamento', 'geometry': 'geometry_region'})

In [9]:
#convertir todos los valores de la columna departamento a minusculas
departamentos['departamento'] = departamentos['departamento'].str.lower()

#convertir los espacios en blanco a guiones bajos
departamentos['departamento'] = departamentos['departamento'].str.replace(' ', '_')

departamentos

     departamento                                    geometry_region
0        amazonas  POLYGON ((-77.81399 -2.99278, -77.81483 -2.995...
1          ancash  POLYGON ((-77.64697 -8.05086, -77.64689 -8.051...
2        apurimac  POLYGON ((-73.74655 -13.17442, -73.7457 -13.17...
3        arequipa  POLYGON ((-71.98109 -14.64062, -71.98093 -14.6...
4        ayacucho  POLYGON ((-74.34843 -12.17503, -74.35 -12.1758...
5       cajamarca  POLYGON ((-78.70034 -4.62769, -78.69817 -4.629...
6          callao  POLYGON ((-77.13504 -11.8182, -77.13484 -11.81...
7           cusco  POLYGON ((-72.9728 -11.25189, -72.97134 -11.25...
8    huancavelica  POLYGON ((-74.57118 -11.9871, -74.57095 -11.98...
9         huanuco  POLYGON ((-75.992 -8.32108, -75.99015 -8.32171...
10            ica  POLYGON ((-75.61136 -12.96649, -75.61103 -12.9...
11          junin  POLYGON ((-75.03564 -10.68232, -75.03436 -10.6...
12    la_libertad  POLYGON ((-77.75753 -6.96579, -77.75638 -6.967...
13     lambayeque  POLYGON ((-79.88373 -5.49283, -79.88265 -5.494...
14           lima  MULTIPOLYGON (((-76.90483 -10.27726, -76.90451...
15         loreto  POLYGON ((-75.10004 -0.08096, -75.09485 -0.081...
16  madre_de_dios  POLYGON ((-70.61346 -10.12964, -70.61359 -10.2...
17       moquegua  POLYGON ((-70.79388 -15.98721, -70.79486 -15.9...
18          pasco  POLYGON ((-74.68005 -9.44727, -74.67872 -9.448...
19          piura  POLYGON ((-81.02621 -4.10594, -81.02557 -4.106...
20           puno  MULTIPOLYGON (((-68.86764 -13.01075, -68.86917...
21     san_martin  POLYGON ((-77.71678 -5.41597, -77.7127 -5.4164...
22          tacna  POLYGON ((-70.26604 -16.77955, -70.26474 -16.7...
23         tumbes  POLYGON ((-80.28521 -3.41276, -80.28406 -3.412...
24        ucayali  POLYGON ((-74.47145 -7.27617, -74.47052 -7.277...

In [10]:
print(final["region"].unique())
print(departamentos["departamento"].unique())

['amazonas' 'ancash' 'apurimac' 'arequipa' 'ayacucho' 'cajamarca' 'callao'
 'cusco' 'huancavelica' 'huanuco' 'ica' 'junin' 'la_libertad' 'lambayeque'
 'lima' 'loreto' 'madre_de_dios' 'moquegua' 'pasco' 'piura' 'puno'
 'san_martin' 'tacna' 'tumbes' 'ucayali']
['amazonas' 'ancash' 'apurimac' 'arequipa' 'ayacucho' 'cajamarca' 'callao'
 'cusco' 'huancavelica' 'huanuco' 'ica' 'junin' 'la_libertad' 'lambayeque'
 'lima' 'loreto' 'madre_de_dios' 'moquegua' 'pasco' 'piura' 'puno'
 'san_martin' 'tacna' 'tumbes' 'ucayali']