In [1]:
import pandas as pd
import numpy as np

In [ ]:
final = pd.read_excel('Health_crime_dta.xlsx' )
final

,Unnamed: 0,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,media_sis,media_dia,categoria_presion,...,nombre_centro_poblado,longitud,latitud,geometry,incidencia_patrimonio,incidencia_libertad,incidencia_seguridad,incidencia_tranquilidad,incidencia_vida,incidencia_otros
0,0,2019,100201,completa,2,mujer,33,100,60,normal,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
1,1,2019,102801,completa,2,mujer,36,110,75,normal,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
2,2,2019,104801,completa,2,mujer,28,134,76,hipertension etapa 1,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
3,3,2019,113601,completa,2,mujer,30,98,65,normal,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
4,4,2019,116701,completa,1,mujer,18,118,72,normal,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,140826,2023,542706001,completa,1,hombre,60,139,80,hipertension etapa 1,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140827,140827,2023,542707401,completa,1,hombre,47,121,59,elevado,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140828,140828,2023,542708901,completa,1,hombre,47,125,76,elevado,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140829,140829,2023,542709201,completa,2,mujer,38,120,76,elevado,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140830,140830,2023,542709401,completa,1,hombre,55,125,79,elevado,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688

In [ ]:
final = final.drop(columns=['Unnamed: 0'])
final

,anio,id_hogar,cod_resultado,cod_persona,sexo,edad,media_sis,media_dia,categoria_presion,diagnostico_hipertension,...,nombre_centro_poblado,longitud,latitud,geometry,incidencia_patrimonio,incidencia_libertad,incidencia_seguridad,incidencia_tranquilidad,incidencia_vida,incidencia_otros
0,2019,100201,completa,2,mujer,33,100,60,normal,no,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
1,2019,102801,completa,2,mujer,36,110,75,normal,no,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
2,2019,104801,completa,2,mujer,28,134,76,hipertension etapa 1,no,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
3,2019,113601,completa,2,mujer,30,98,65,normal,no,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
4,2019,116701,completa,1,mujer,18,118,72,normal,no,...,chachapoyas,-77.873830,-6.22332,POINT (-77.87383 -6.22332),631.807919,169.630281,147.453305,4.482580,973.899585,617.888327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
140826,2023,542706001,completa,1,hombre,60,139,80,hipertension etapa 1,si,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140827,2023,542707401,completa,1,hombre,47,121,59,elevado,no,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140828,2023,542708901,completa,1,hombre,47,125,76,elevado,si,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140829,2023,542709201,completa,2,mujer,38,120,76,elevado,no,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688
140830,2023,542709401,completa,1,hombre,55,125,79,elevado,no,...,esperanza,-70.713086,-9.77104,POINT (-70.71308629 -9.77104006),1270.341325,306.265774,561.513823,8.609241,880.055737,925.971688